"""Controller discovery and interaction library (ticket #43).

The controller is a resource-mode middleware instance that discovers other resources,
opens their REST datamodels, and writes to parameter paths. It registers itself as a
ControlStationService so it appears in its own discovery list.

Discovery uses the OGM's class-based traversal — no raw SPARQL in the standard path.
Liveness is determined by the presence of svc:address on the resource's Service.
Parameter writes go over REST to the recursive routes generated by ADR 0017.
"""

from __future__ import annotations

import asyncio
import functools
import logging
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

import anyio
import httpx
from graph_db_interface import IRI

from kapps_semantic_middleware import Mode, SemanticMiddleware
from kapps_semantic_middleware.vocabulary import CFC, SVC

logger = logging.getLogger(__name__)


@dataclass
class ResourceInfo:
    """Metadata about a discovered resource, for listing in discovery.

    Attributes:
        resource_iri: The individual's IRI.
        resource_type: The class IRI (e.g. tu:TransferUnit).
        label: Human-readable label, if present.
        address: The service's svc:address — presence means live, absence means offline.
        last_heartbeat: The service's svc:lastHeartbeat timestamp, if present.
    """

    resource_iri: IRI
    """The individual's IRI."""

    resource_type: IRI
    """The class IRI (e.g. tu:TransferUnit)."""

    label: Optional[str]
    """Human-readable label, if present."""

    address: Optional[str]
    """The service's svc:address — presence means live, absence means offline."""

    last_heartbeat: Optional[str]
    """The service's svc:lastHeartbeat timestamp, if present."""

    @property
    def is_live(self) -> bool:
        """Live iff svc:address is present (MVP liveness, ticket #43)."""
        return self.address is not None


class Controller(SemanticMiddleware):
    """A resource-mode middleware that discovers and controls other resources.

    The controller:
    - Discovers resources by class IRI (e.g. tu:TransferUnit lists TransferUnits)
    - Opens a resource's REST datamodel via GET /resource/{id}/
    - Writes to parameter paths via PUT to recursive routes (ADR 0017)
    - Registers itself as a ControlStationService so it appears in discovery

    Unlike device-facing middleware instances, the controller does not wire semantic
    connectors to physical devices. It uses REST to interact with other resources'
    exposed interfaces.

    Usage::

        controller = Controller(
            mode=Mode.RESOURCE,
            resource_iri=IRI("http://example.org/ControlStation1"),
            service_class=CFC.Resource,
            ogm=ogm,
            host="127.0.0.1",
            port=8080,
        )
        await controller.initialize()

        # Discover all TransferUnits
        units = controller.discover_resources(tu.TransferUnit)

        # Open a specific unit's datamodel
        datamodel = await controller.open_resource(units[0].address)

        # Write to a parameter path
        await controller.set_parameter(units[0].address, "/ConveyorBelt_1/conveyorSpeed", 50)
    """

    def __init__(
        self,
        *,
        resource_iri: str,
        service_class: Optional[str] = None,
        ogm: Any = None,
        host: str = "127.0.0.1",
        port: int = 8000,
        named_graph: Optional[str] = None,
        heartbeat_interval: Optional[float] = 30.0,
        staleness_threshold: float = 90.0,
        activity_feed: bool = False,
        activity_capacity: int = 200,
    ) -> None:
        """Initialize the controller middleware.

        Args:
            resource_iri: The IRI of this control station resource.
            service_class: The service class IRI (defaults to cfc:Resource).
            ogm: The OGM instance for graph interactions.
            host: Host to bind the REST API on.
            port: Port to bind the REST API on.
            named_graph: Named graph for resource data.
            heartbeat_interval: Interval for heartbeat updates.
            staleness_threshold: Threshold for considering a resource stale.
            activity_feed: Whether to enable activity feed.
            activity_capacity: Capacity of the activity feed ring buffer.
        """
        # The controller is a resource-mode instance with its own Service registration.
        # It deliberately does NOT use class_scope or autoregister_connectors because
        # it has no physical device to connect to — it talks REST to other resources.
        super().__init__(
            mode=Mode.RESOURCE,
            resource_iri=resource_iri,
            service_class=service_class or str(CFC.Resource),
            ogm=ogm,
            host=host,
            port=port,
            named_graph=named_graph,
            heartbeat_interval=heartbeat_interval,
            staleness_threshold=staleness_threshold,
            class_scope=None,  # No device interface to prune
            autoregister_connectors=False,  # No connectors for the controller itself
            activity_feed=activity_feed,
            activity_capacity=activity_capacity,
        )

    def discover_resources(self, resource_class: Any) -> List[ResourceInfo]:
        """List all individuals of resource_class with their service metadata.

        This is the standard discovery path using ontology traversal — the SPARQL
        is encapsulated so callers don't write it, but under the hood it navigates
        the ontology graph to find individuals and their associated Service nodes.

        Args:
            resource_class: The resource class IRI or class object (e.g. tu:TransferUnit).

        Returns:
            List of ResourceInfo with address, heartbeat, and liveness status.
        """
        resource_class_iri = IRI(resource_class) if not isinstance(resource_class, IRI) else resource_class

        results: List[ResourceInfo] = []

        try:
            # Query for all individuals of the resource class that have a Service linked.
            # This follows the pattern used in registration.py's find_resource_operations.
            sparql = f"""
            SELECT ?resource ?label ?svc ?addr ?hb WHERE {{
                ?resource a <{resource_class_iri}> .
                OPTIONAL {{ ?resource <{CFC.hasCapability}> ?cap . }}
                OPTIONAL {{ ?svc <{SVC.isServiceOf}> ?resource . }}
                OPTIONAL {{ ?svc <{SVC.address}> ?addr . }}
                OPTIONAL {{ ?svc <{SVC.lastHeartbeat}> ?hb . }}
                OPTIONAL {{ ?resource <http://www.w3.org/2000/01/rdf-schema#label> ?label . }}
            }}
            """
            result = self.ogm.db.query(sparql, convert_bindings=True)
            bindings = (
                result.get("results", {}).get("bindings", []) if isinstance(result, dict) else []
            )

            seen_resources = set()
            for binding in bindings:
                resource_iri_str = str(binding["resource"]["value"])
                if resource_iri_str in seen_resources:
                    continue
                seen_resources.add(resource_iri_str)

                resource_iri = IRI(resource_iri_str)
                label = binding.get("label", {}).get("value") if binding.get("label") else None
                address = binding.get("addr", {}).get("value") if binding.get("addr") else None
                last_heartbeat = binding.get("hb", {}).get("value") if binding.get("hb") else None

                results.append(ResourceInfo(
                    resource_iri=resource_iri,
                    resource_type=resource_class_iri,
                    label=label,
                    address=address,
                    last_heartbeat=last_heartbeat,
                ))

        except Exception as e:
            logger.warning("Failed to discover resources of class %s: %s", resource_class_iri, e)
            # Return empty list on error — discovery is best-effort

        return results

    def _get_service_info(self, resource_iri: IRI) -> Dict[str, Optional[str]]:
        """Get the service metadata for a resource.

        Queries the graph for the Service linked to this resource via svc:isServiceOf,
        returning address and lastHeartbeat.

        Args:
            resource_iri: The resource's IRI.

        Returns:
            Dict with 'address' and 'lastHeartbeat' keys, both possibly None.
        """
        result = {"address": None, "lastHeartbeat": None}

        try:
            # Query for the Service linked to this resource via svc:isServiceOf.
            # This follows the pattern used in registration.py's services_of_resource.
            sparql = f"""
            SELECT ?svc ?addr ?hb WHERE {{
                ?svc <{SVC.isServiceOf}> <{resource_iri}> .
                OPTIONAL {{ ?svc <{SVC.address}> ?addr . }}
                OPTIONAL {{ ?svc <{SVC.lastHeartbeat}> ?hb . }}
            }}
            """
            db_result = self.ogm.db.query(sparql, convert_bindings=True)
            bindings = (
                db_result.get("results", {}).get("bindings", []) if isinstance(db_result, dict) else []
            )

            if bindings:
                binding = bindings[0]
                addr_val = binding.get("addr", {}).get("value") if binding.get("addr") else None
                hb_val = binding.get("hb", {}).get("value") if binding.get("hb") else None

                if addr_val:
                    result["address"] = str(addr_val)
                if hb_val:
                    result["lastHeartbeat"] = str(hb_val)

        except Exception as e:
            logger.debug("Failed to get service info for %s: %s", resource_iri, e)

        return result

    async def open_resource(self, base_url: str) -> Dict[str, Any]:
        """GET the resource's full datamodel tree via REST.

        Fetches the resource's REST datamodel from its base URL. This is the
        entry point for reading a resource's state before writing to parameters.

        Args:
            base_url: The resource's base URL (from ResourceInfo.address).

        Returns:
            The JSON datamodel tree returned by GET {base_url}/resource/.
        """
        async with httpx.AsyncClient(timeout=30.0) as client:
            url = f"{base_url}/resource/"
            response = await client.get(url)
            response.raise_for_status()
            return response.json()

    async def set_parameter(self, base_url: str, path: str, value: Any) -> Dict[str, str]:
        """PUT a value to a structural parameter path.

        Writes to a parameter using the recursive route structure from ADR 0017.
        The path is literal segments matching the datamodel tree structure.

        Args:
            base_url: The resource's base URL.
            path: The parameter path (e.g., "/ConveyorBelt_1/conveyorSpeed").
            value: The value to write.

        Returns:
            Response JSON from the PUT request.
        """
        async with httpx.AsyncClient(timeout=30.0) as client:
            url = f"{base_url}{path}"
            response = await client.put(url, json=value)
            response.raise_for_status()
            return response.json()

    async def get_parameter(self, base_url: str, path: str) -> Any:
        """GET a value from a structural parameter path.

        Reads a parameter using the recursive route structure from ADR 0017.

        Args:
            base_url: The resource's base URL.
            path: The parameter path (e.g., "/ConveyorBelt_1/conveyorSpeed").

        Returns:
            The parameter value.
        """
        async with httpx.AsyncClient(timeout=30.0) as client:
            url = f"{base_url}{path}"
            response = await client.get(url)
            response.raise_for_status()
            return response.json()