"""Controller discovery and interaction library (ticket #43).

The controller is a resource-mode middleware instance that discovers other resources,
opens their REST datamodels, and writes to parameter paths. It registers itself as a
ControlStationService so it appears in its own discovery list.

Discovery uses the OGM's class-based traversal. It does not use raw SPARQL in the standard path.
The presence of svc:address on the resource's Service determines liveness.
Parameter writes go over REST to the recursive routes generated by ADR 0017.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Sequence, Tuple

import httpx
from graph_db_interface import IRI

from kapps_semantic_middleware import Mode, SemanticMiddleware
from kapps_semantic_middleware.vocabulary import CFC, SVC

logger = logging.getLogger(__name__)


@dataclass
class ResourceInfo:
    """Metadata about a discovered resource, for listing in discovery.

    Attributes:
        resource_iri: The individual's IRI.
        resource_type: The class IRI (e.g. tu:TransferUnit).
        label: Human-readable label, if present.
        address: The service's svc:address — presence means live, absence means offline.
        last_heartbeat: The service's svc:lastHeartbeat timestamp, if present.
    """

    resource_iri: IRI
    """The individual's IRI."""

    resource_type: IRI
    """The class IRI (e.g. tu:TransferUnit)."""

    label: Optional[str]
    """Human-readable label, if present."""

    address: Optional[str]
    """The service's svc:address. Presence means live. Absence means offline."""

    last_heartbeat: Optional[str]
    """The service's svc:lastHeartbeat timestamp, if present."""

    @property
    def is_live(self) -> bool:
        """Live iff svc:address is present (MVP liveness, ticket #43)."""
        return self.address is not None


class Controller(SemanticMiddleware):
    """A resource-mode middleware that discovers and controls other resources.

    The controller does four things. It discovers resources by class IRI, so naming
    tu:TransferUnit lists TransferUnits. It opens a resource's REST datamodel, with a
    GET to /{Model}/{lined_id}. It writes to a parameter, with a PUT to a recursive
    route (ADR 0017). It registers itself as a ControlStationService, so it appears
    in its own discovery list.

    Unlike device-facing middleware instances, the controller does not wire semantic
    connectors to physical devices. It uses REST to reach other resources' exposed
    interfaces. It always uses the address that discovery found for the resource,
    never its own address.

    Route paths mirror the datamodel tree (ADR 0017). The caller supplies each
    (field_name, child_id) hop. Each hop comes from the JSON tree that
    open_resource() returns. The controller mangles only the individual IDs, with
    IRI.lined. Field names stay literal. ADR 0017 shows a full example path.

    Usage::

        controller = Controller(
            resource_iri="http://example.org/ControlStation1",
            service_class=CFC.Resource,
            ogm=ogm,
            host="127.0.0.1",
            port=8080,
        )
        # A real deployment fires this through the FastAPI app's own
        # lifespan. Uvicorn starts the lifespan. A test can call it
        # directly, the same way test_liveness_integration.py does.
        await controller._register_service()

        # Discover all TransferUnits
        units = controller.discover_resources(tu.TransferUnit)

        # Open a specific unit's datamodel (GET goes to the unit's own address, not ours)
        datamodel = await controller.open_resource(units[0])

        # Navigate to the left belt in datamodel["tu:hasConveyorBelt"], then write its speed:
        steps = [("tu:hasConveyorBelt", "https://example.org/tui#ConveyorBelt1_left")]
        await controller.set_parameter(
            units[0],
            steps,
            "tu:hasConveyorSpeed",
            [{"inf:hasValue": [50.0], "inf:accessMode": ["readwrite"]}],
        )
    """

    def __init__(
        self,
        *,
        resource_iri: str,
        service_class: Optional[str] = None,
        ogm: Any = None,
        host: str = "127.0.0.1",
        port: int = 8000,
        named_graph: Optional[str] = None,
        heartbeat_interval: Optional[float] = 30.0,
        staleness_threshold: float = 90.0,
        activity_feed: bool = False,
        activity_capacity: int = 200,
    ) -> None:
        """Initialize the controller middleware.

        Args:
            resource_iri: The IRI of this control station resource.
            service_class: The Service class IRI. It must be svc:Service or
                a subclass. It defaults to svc:Service itself. Ticket #66's
                fac:ControlStationService is not yet an ontology class in
                this repo, so pass it explicitly once that class exists.
            ogm: The OGM instance for graph interactions.
            host: Host to bind the REST API on.
            port: Port to bind the REST API on.
            named_graph: Named graph for resource data.
            heartbeat_interval: Interval for heartbeat updates.
            staleness_threshold: Threshold for considering a resource stale.
            activity_feed: Whether to enable activity feed.
            activity_capacity: Capacity of the activity feed ring buffer.
        """
        # The controller is a resource-mode instance with its own Service registration.
        # It deliberately does NOT use class_scope or autoregister_connectors because
        # it has no physical device to connect to — it talks REST to other resources.
        #
        # service_class must be svc:Service or a subclass (register_service enforces
        # this against the graph). cfc:Resource, the original default here, is not
        # one, and register_service rejected it outright. svc:Service always passes,
        # since assert_class_registered short-circuits when class_iri == base_iri.
        super().__init__(
            mode=Mode.RESOURCE,
            resource_iri=resource_iri,
            service_class=service_class or str(SVC.Service),
            ogm=ogm,
            host=host,
            port=port,
            named_graph=named_graph,
            heartbeat_interval=heartbeat_interval,
            staleness_threshold=staleness_threshold,
            class_scope=None,  # No device interface to prune
            autoregister_connectors=False,  # No connectors for the controller itself
            activity_feed=activity_feed,
            activity_capacity=activity_capacity,
        )

    def discover_resources(self, resource_class: Any) -> List[ResourceInfo]:
        """List all individuals of resource_class with their service metadata.

        This is the standard discovery path. It uses ontology traversal, so the
        caller writes no SPARQL. Internally, it walks the ontology graph and finds
        each individual and its linked Service node.

        Args:
            resource_class: The resource class IRI or class object (e.g. tu:TransferUnit).

        Returns:
            List of ResourceInfo with address, heartbeat, and liveness status.
        """
        resource_class_iri = IRI(resource_class) if not isinstance(resource_class, IRI) else resource_class

        results: List[ResourceInfo] = []

        try:
            # Query for all individuals of the resource class that have a Service linked.
            sparql = f"""
            SELECT ?resource ?label ?svc ?addr ?hb WHERE {{
                ?resource a <{resource_class_iri}> .
                OPTIONAL {{ ?svc <{SVC.isServiceOf}> ?resource . }}
                OPTIONAL {{ ?svc <{SVC.address}> ?addr . }}
                OPTIONAL {{ ?svc <{SVC.lastHeartbeat}> ?hb . }}
                OPTIONAL {{ ?resource <http://www.w3.org/2000/01/rdf-schema#label> ?label . }}
            }}
            """
            result = self.ogm.db.query(sparql, convert_bindings=True)
            bindings = (
                result.get("results", {}).get("bindings", []) if isinstance(result, dict) else []
            )

            seen_resources = set()
            for binding in bindings:
                # With convert_bindings=True, each binding value is already a converted
                # Python object, such as an IRI or a str. It is not a raw {"value": ...}
                # dict. Index it directly. This matches registration.py's own pattern,
                # for example find_resource_operations.
                resource_iri_str = str(binding["resource"])
                if resource_iri_str in seen_resources:
                    continue
                seen_resources.add(resource_iri_str)

                resource_iri = IRI(resource_iri_str)
                label = binding.get("label")
                address = binding.get("addr")
                last_heartbeat = binding.get("hb")

                results.append(ResourceInfo(
                    resource_iri=resource_iri,
                    resource_type=resource_class_iri,
                    label=str(label) if label is not None else None,
                    address=str(address) if address is not None else None,
                    last_heartbeat=str(last_heartbeat) if last_heartbeat is not None else None,
                ))

        except Exception as e:
            logger.warning("Failed to discover resources of class %s: %s", resource_class_iri, e)
            # Return empty list on error. Discovery is best-effort.

        return results

    def _get_service_info(self, resource_iri: IRI) -> Dict[str, Optional[str]]:
        """Get the service metadata for a resource.

        Queries the graph for the Service linked to this resource via svc:isServiceOf,
        returning address and lastHeartbeat.

        Args:
            resource_iri: The resource's IRI.

        Returns:
            Dict with 'address' and 'lastHeartbeat' keys, both possibly None.
        """
        result: Dict[str, Optional[str]] = {"address": None, "lastHeartbeat": None}

        try:
            # Query for the Service linked to this resource via svc:isServiceOf.
            sparql = f"""
            SELECT ?svc ?addr ?hb WHERE {{
                ?svc <{SVC.isServiceOf}> <{resource_iri}> .
                OPTIONAL {{ ?svc <{SVC.address}> ?addr . }}
                OPTIONAL {{ ?svc <{SVC.lastHeartbeat}> ?hb . }}
            }}
            """
            db_result = self.ogm.db.query(sparql, convert_bindings=True)
            bindings = (
                db_result.get("results", {}).get("bindings", []) if isinstance(db_result, dict) else []
            )

            if bindings:
                binding = bindings[0]
                # Same convert_bindings=True shape as discover_resources. Index directly.
                addr_val = binding.get("addr")
                hb_val = binding.get("hb")

                if addr_val is not None:
                    result["address"] = str(addr_val)
                if hb_val is not None:
                    result["lastHeartbeat"] = str(hb_val)

        except Exception as e:
            logger.debug("Failed to get service info for %s: %s", resource_iri, e)

        return result

    @staticmethod
    def _extract_local_name(iri: IRI) -> str:
        """Extract the fragment/local name from an IRI (after the '#').

        Mirrors IRI.short's fragment-split logic. Use this to derive the {Model}
        segment of a REST route from a resource's class IRI. A resource
        materializes as a pydantic model, whose class name equals its ontology
        class's local name. For example, tu:TransferUnit materializes as
        TransferUnit. This matches the route shape in test_recursive_rest_router.py.

        Args:
            iri: The IRI to extract the local name from.

        Returns:
            The fragment portion (e.g. "TransferUnit" from "...#TransferUnit").
        """
        return str(iri).rsplit("#", 1)[-1]

    @staticmethod
    def _build_parameter_path(
        resource_class_local_name: str,
        resource_iri: IRI,
        steps: Sequence[Tuple[str, str]],
        terminal_field: str,
    ) -> str:
        """Build the structural REST path for a parameter from known (field, child_id) hops.

        Mirrors rest_router.py's _accumulate_routes path shape exactly:
        /{Model}/{lined_root}/{field}/{lined_child}/.../{field}. Field names stay literal.
        Only individual IDs are mangled, via IRI.lined (ADR 0017, ADR 0021).

        The caller already knows each hop's child id. It typically reads the id off
        the JSON tree that open_resource() returned. This method only assembles path
        segments. It does not search a tree. For a version that searches and
        validates a fetched tree, see _derive_parameter_path.

        Args:
            resource_class_local_name: Fragment of the resource's class IRI (e.g. "TransferUnit").
            resource_iri: The root resource's own IRI.
            steps: Sequence of (field_name, child_id) hops to navigate the tree.
            terminal_field: The final field name (the parameter itself).

        Returns:
            The structural URL path.
        """
        path_parts = ["", resource_class_local_name, IRI(resource_iri).lined]
        for field_name, child_id in steps:
            path_parts.append(field_name)
            path_parts.append(IRI(child_id).lined)
        path_parts.append(terminal_field)
        return "/".join(path_parts)

    @staticmethod
    def _derive_parameter_path(
        datamodel_tree: Dict[str, Any],
        resource_class_local_name: str,
        resource_iri: IRI,
        steps: Sequence[Tuple[str, str]],
        terminal_field: str,
    ) -> str:
        """Derive a structural REST URL for a parameter by traversing a fetched datamodel tree.

        Mirrors rest_router.py's _accumulate_routes logic. It operates on the plain
        dict/list JSON-tree that open_resource() returns, not on pydantic models.
        This method checks that every hop's child id exists in the tree, then
        builds the path. Use this method, not _build_parameter_path, when the ids
        come from outside the tree and need a check.

        A terminal parameter is a field whose value is a list of dicts WITHOUT an "id" key
        (they carry hasValue/hasUnit/accessMode instead). A non-terminal field's value is a
        list of dicts WITH "id" keys, and recursion continues into the matching child.

        Args:
            datamodel_tree: The full JSON tree from open_resource().
            resource_class_local_name: Fragment of the resource's class IRI (e.g. "TransferUnit").
            resource_iri: The root resource's own IRI.
            steps: Sequence of (field_name, child_id) hops to navigate the tree.
            terminal_field: The final field name (the parameter itself).

        Returns:
            The structural URL path.

        Raises:
            ValueError: A step's field is not a list, or its child_id is not present.
        """
        current_level = datamodel_tree
        for field_name, child_id in steps:
            field_value = current_level.get(field_name, [])
            if not isinstance(field_value, list):
                raise ValueError(f"Field {field_name} is not a list in the datamodel tree")

            child_dict = next(
                (item for item in field_value if isinstance(item, dict) and item.get("id") == child_id),
                None,
            )
            if child_dict is None:
                raise ValueError(f"Child with id {child_id} not found under field {field_name}")

            current_level = child_dict

        return Controller._build_parameter_path(
            resource_class_local_name, resource_iri, steps, terminal_field
        )

    async def open_resource(self, resource_info: ResourceInfo) -> Dict[str, Any]:
        """GET the resource's full datamodel tree via REST.

        Fetches the resource's REST datamodel from the resource's own address,
        resource_info.address. It never uses the controller's own address. The
        request targets the top-level route, /{Model}/{lined_id}. Model is the
        class IRI's fragment. lined_id is IRI(resource_iri).lined. This is the
        entry point for reading a resource's state, before deriving parameter
        paths structurally.

        Args:
            resource_info: The ResourceInfo from discover_resources(), carrying resource_type
                (for the Model segment), resource_iri (for the id segment), and address (the
                resource's own base URL — the actual GET target).

        Returns:
            The JSON datamodel tree returned by GET {resource_info.address}/{Model}/{lined_id}.
        """
        model_name = self._extract_local_name(resource_info.resource_type)
        lined_id = IRI(resource_info.resource_iri).lined
        base_url = resource_info.address

        async with httpx.AsyncClient(timeout=30.0) as client:
            url = f"{base_url}/{model_name}/{lined_id}"
            response = await client.get(url)
            response.raise_for_status()
            return response.json()

    async def set_parameter(
        self,
        resource_info: ResourceInfo,
        steps: Sequence[Tuple[str, str]],
        terminal_field: str,
        value: List[Dict[str, Any]],
    ) -> Dict[str, str]:
        """PUT a value to a structural parameter path on the resource's own address.

        Writes to a parameter, using the recursive route structure from ADR 0017.
        The path comes from the resource's class and the caller's navigation
        steps, never from an arbitrary string. Per ADR 0017, a PUT must send
        exactly what a GET returns: a list of parameter dicts, for example
        [{"inf:hasValue": [...], "inf:accessMode": [...]}]. Read the dict from
        open_resource or get_parameter, change its value, then send the whole
        list back. Do not send a bare scalar.

        Args:
            resource_info: The target resource (its address is the PUT target — the
                controller's own address is never used here).
            steps: Sequence of (field_name, child_id) hops to navigate the tree.
            terminal_field: The parameter field name (the leaf segment).
            value: The list-of-dicts value to write (echo semantics: what GET returned, mutated).

        Returns:
            Response JSON from the PUT request.
        """
        path = self._build_parameter_path(
            self._extract_local_name(resource_info.resource_type),
            resource_info.resource_iri,
            steps,
            terminal_field,
        )
        url = f"{resource_info.address}{path}"

        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.put(url, json=value)
            response.raise_for_status()
            return response.json()

    async def get_parameter(
        self,
        resource_info: ResourceInfo,
        steps: Sequence[Tuple[str, str]],
        terminal_field: str,
    ) -> Any:
        """GET a value from a structural parameter path on the resource's own address.

        Reads a parameter using the recursive route structure from ADR 0017, at the same
        structural path set_parameter would PUT to.

        Args:
            resource_info: The target resource (its address is the GET target).
            steps: Sequence of (field_name, child_id) hops to navigate the tree.
            terminal_field: The parameter field name.

        Returns:
            The parameter value (a list of dicts per RDF multiplicity, ADR 0017).
        """
        path = self._build_parameter_path(
            self._extract_local_name(resource_info.resource_type),
            resource_info.resource_iri,
            steps,
            terminal_field,
        )
        url = f"{resource_info.address}{path}"

        async with httpx.AsyncClient(timeout=30.0) as client:
            response = await client.get(url)
            response.raise_for_status()
            return response.json()
